// use std::path::PathBuf;

use serde_json::Value;
use std::{
    collections::HashMap,
    fs::{self, File},
    io::Write,
};
use wasm_bindgen::prelude::*;
use xml::{reader::XmlEvent, EventReader};

// parse string into array of words (called tokens)
#[derive(Debug)]
struct Lexer<'a> {
    source: &'a [char],
}
impl<'a> Lexer<'a> {
    pub fn new(source: &'a [char]) -> Self {
        Self { source }
    }

    //pop 0..n of source,
    fn chop_left(&mut self, n: usize) -> &'a [char] {
        let result = &self.source[0..n];
        self.source = &self.source[n..];
        result
    }

    //move index while predicate holds
    fn move_idx_while(&mut self, predicate: fn(&char) -> bool) -> usize {
        let mut n = 0;
        while n < self.source.len() && predicate(&self.source[n]) {
            n += 1;
        }
        n
    }
    fn trim_white_space(&mut self) {
        if self.source.len() == 0 {
            return;
        }
        while self.source[0].is_whitespace() {
            if self.source.len() > 1 {
                self.source = &self.source[1..];
            } else {
                self.source = &[];
                return;
            }
        }
    }

    fn parse_next_token(&mut self) -> Option<&'a [char]> {
        self.trim_white_space();
        if self.source.len() == 0 {
            return None;
        }
        if self.source[0].is_alphabetic() {
            let end_pos = self.move_idx_while(|x| x.is_alphabetic());
            Some(self.chop_left(end_pos))
        } else if self.source[0].is_numeric() {
            let end_pos = self.move_idx_while(|x| x.is_numeric());
            Some(self.chop_left(end_pos))
        } else {
            Some(self.chop_left(1))
        }
    }
    fn to_hash_map(tok: String, hmap: &mut HashMap<String, i32>) {
        if let Some(_freq) = hmap.get_mut(&tok) {
            // hmap.insert(tok, _freq + 1);
            *_freq += 1;
        } else {
            hmap.insert(tok, 1);
        }
    }
}

fn read_all_xml(file_path: &str) -> Result<String, std::io::Error> {
    let mut result = String::from("");
    let file = File::open(file_path)?;
    let parser = EventReader::new(file);
    for e in parser {
        match e {
            Ok(XmlEvent::Characters(s)) => {
                result.push_str(&s);
            }
            _ => {}
        }
    }
    Ok(result)
}
impl<'a> Iterator for Lexer<'a> {
    type Item = &'a [char];

    fn next(&mut self) -> Option<Self::Item> {
        self.parse_next_token()
    }
}
fn c_to_s<'a>(c: &'a [char]) -> String {
    c.iter().collect::<String>()
}
type TFMap = HashMap<String, i32>; //Term-frequency map
type DirMap = HashMap<String, TFMap>; //File-TFMap map
type FFMap = HashMap<String, f32>; //File-Frequency map
const PARSE_LIMIT: i8 = 10;
const DATA_PATH: &str = "gl4-datasettest.json";

fn test_program() {
    let mut map = HashMap::new();
    // map.insert("name", "John Doe");
    let mut map2 = HashMap::new();
    map2.insert("name", 3);
    map2.insert("name2", 4);

    let mut map3 = HashMap::new();
    map2.insert("name", 3);
    map2.insert("name2", 4);
    map3.insert("name2", 4);
    // map.insert("name", "Duy");
    map.insert("name3", map3);
    map.insert("name2", map2);
    // map.insert("age", 30);

    let json = serde_json::to_string(&map).unwrap();
    println!("{}", json);
}
pub fn tf_compute(term: &str, tfmap: TFMap) -> f32 {
    let a = tfmap.get(term).unwrap_or_else(|| &0).to_owned() as f32;
    let b = tfmap.values().sum::<i32>() as f32;
    a / b
}

// #[used]
pub fn parse_to_ffmap(term: String, json: &str) -> Result<FFMap, std::io::Error> {
    let mut result: FFMap = HashMap::new();
    let dirmap = load_json_to_hashmap(json)?;
    for (path, tfmap) in dirmap {
        result.insert(path, tf_compute(&term, tfmap));
    }
    Ok(result)
}
fn test2program() {
    let dir_path = "docs.gl/gl4/";
    let dir = fs::read_dir(dir_path).expect("cant read dir");
    let mut dir_hmap: DirMap = HashMap::new();

    for file in dir {
        // limit max files parse
        if dir_hmap.len() == PARSE_LIMIT as usize {
            break;
        }

        // parse 1 file to tfmap
        let file = file.expect("Cant read file");
        let file_path = file.path().to_string_lossy().into_owned();

        let content = read_all_xml(&file_path)
            .expect("cant read file")
            .chars()
            .collect::<Vec<_>>();
        let parser = Lexer::new(&content);
        let mut tfmap: TFMap = HashMap::new();

        for token in parser {
            let token = c_to_s(token);
            Lexer::to_hash_map(token, &mut tfmap);
        }

        // index parsed tfmap
        dir_hmap.insert(file_path.clone(), tfmap);
        println!("{} parsed", file_path);
    }

    let result = parse_dir_to_json(&dir_hmap).expect("cant parse");
    // println!("{}", result);
    save_json_to_disk(result, "gl4-datasettest.json");
    // let hmp = load_json_to_hashmap().expect("no json");
    // let newjs = parse_dir_to_json(&hmp).expect("cant parse");
    // save_json_to_disk(newjs, "gl4-datasettest2.json");
}
fn main_program() {
    let dir_path = "docs.gl/gl4/";
    let dir = fs::read_dir(dir_path).expect("cant read dir");
    let mut dir_hmap: DirMap = HashMap::new();

    for file in dir {
        // limit max files parse
        if dir_hmap.len() == PARSE_LIMIT as usize {
            break;
        }

        // parse 1 file to tfmap
        let file = file.expect("Cant read file");
        let file_path = file.path().to_string_lossy().into_owned();

        let content = read_all_xml(&file_path)
            .expect("cant read file")
            .chars()
            .collect::<Vec<_>>();
        let parser = Lexer::new(&content);
        let mut tfmap: TFMap = HashMap::new();

        for token in parser {
            let token = c_to_s(token);
            Lexer::to_hash_map(token, &mut tfmap);
        }

        // index parsed tfmap
        dir_hmap.insert(file_path.clone(), tfmap);
        println!("{} parsed", file_path);
    }
    let result = parse_dir_to_json(&dir_hmap).expect("cant parse");
    // println!("{}", result);
    save_json_to_disk(result, "gl4-dataset.json");
}

// JSON HELPERS ===>

pub fn save_json_to_disk(data: String, filename: &str) {
    let mut file = File::create(filename).expect("Cant create");
    file.write_all(data.as_bytes()).expect("cant write");
    println!("Saved to disk!");
}

pub fn parse_dir_to_json(
    hmap: &HashMap<String, HashMap<String, i32>>,
) -> Result<String, std::io::Error> {
    let json = serde_json::to_string_pretty(hmap)?;
    Ok(json)
}

pub fn load_json_to_hashmap(data: &str) -> Result<DirMap, std::io::Error> {
    let data = serde_json::from_str(&data)?;
    let mut hmap: DirMap = HashMap::new();

    if let Value::Object(inner) = data {
        for (key, value) in inner {
            match value {
                Value::Object(_inner) => {
                    let mut tf_map: TFMap = HashMap::new();
                    for (_key, _value) in _inner {
                        if let Value::Number(freq) = _value {
                            tf_map.insert(_key, freq.as_i64().expect("Cant cast number") as i32);
                        }
                    }
                    hmap.insert(key, tf_map);
                }
                _ => (),
            }
        }
    }
    Ok(hmap)
}
#[wasm_bindgen]
extern "C" {
    pub fn alert(s: &str);
}

#[wasm_bindgen]
pub fn ranking_docs(term: &str) -> String {
    let mut result: Vec<String> = vec![];

    let ffmap = parse_to_ffmap(term.to_string(), JSONFULL).expect("cant parse");
    let mut ffmap = ffmap.into_iter().collect::<Vec<(String, f32)>>();
    ffmap.sort_by(|a, b| b.1.partial_cmp(&a.1).unwrap());
    for (path, freq) in ffmap {
        result.push(path);
    }
    result.join("\n")
}

const JSONFULL: &str = r#"
{
  "docs.gl/gl4/glBindImageTextures.xhtml": {
    ".": 39,
    "first": 7,
    "bound": 5,
    "map": 1,
    "NULL": 2,
    "The": 1,
    "R": 1,
    "MAP": 3,
    "glTexBuffer": 1,
    "glTexParameterCopyright": 1,
    "14": 1,
    "GLsizei": 1,
    "whose": 1,
    "}": 5,
    "That": 1,
    "glIsTexture": 1,
    "License": 1,
    "unitsC": 1,
    "starting": 1,
    "had": 1,
    "GetsglGet": 1,
    "pipelinestall": 1,
    "—": 1,
    "images": 2,
    "binding": 2,
    "WRITE": 1,
    "glGenTextures": 2,
    "https": 1,
    "sized": 1,
    "1": 4,
    "via": 1,
    "is": 21,
    "object": 3,
    "it": 1,
    "This": 1,
    "24": 1,
    "Name": 1,
    "i": 8,
    "TEXTURE": 12,
    "NameglBindImageTextures": 1,
    "=": 4,
    "not": 3,
    "23": 1,
    "See": 1,
    "DescriptionglBindImageTextures": 1,
    "zeros": 1,
    "following": 1,
    "13": 2,
    "width": 1,
    "found": 1,
    "03": 1,
    "subject": 1,
    "Each": 1,
    "may": 1,
    "MULTISAMPLE": 2,
    "access": 1,
    "conditions": 1,
    "3": 3,
    "layer": 1,
    "still": 1,
    "glBindTextures": 2,
    "2013": 1,
    "CUBE": 3,
    "Any": 1,
    "available": 1,
    "units": 4,
    "because": 1,
    "When": 1,
    "referenced": 1,
    "non": 2,
    "]": 3,
    "org": 1,
    ")": 7,
    "count": 6,
    "glBindTexture": 1,
    "Associated": 1,
    "ErrorsGL": 1,
    "an": 6,
    "previously": 2,
    "sequence": 1,
    "appears": 1,
    "set": 2,
    "openpub": 1,
    "FALSE": 1,
    "OPERATION": 4,
    "DMultisample": 2,
    "0": 8,
    "read": 2,
    "AlsoglBindTexture": 1,
    "Group": 1,
    "name": 4,
    "at": 3,
    "8": 2,
    "glDeleteTextures": 1,
    "format": 4,
    "glTexStorage": 5,
    "if": 9,
    "(": 7,
    "value": 1,
    "44": 1,
    "texture": 15,
    "else": 1,
    "invalid": 1,
    "Copyright": 1,
    "reset": 1,
    "specified": 2,
    "individually": 1,
    "even": 1,
    "const": 1,
    "unit": 4,
    "INVALID": 4,
    "2": 7,
    "lookupInternalFormat": 1,
    "number": 5,
    "Version": 1,
    "Specifies": 3,
    "binds": 1,
    "from": 4,
    "considered": 1,
    "opencontent": 1,
    "4": 2,
    "checked": 1,
    "argument": 1,
    "material": 1,
    "least": 1,
    "<": 1,
    "in": 9,
    "depth": 1,
    "5": 1,
    "error": 3,
    "[": 3,
    "a": 6,
    "$": 2,
    "If": 2,
    "generated": 6,
    "NotesglBindImageTextures": 1,
    "write": 1,
    "Parametersfirst": 1,
    "than": 1,
    "containing": 1,
    "v": 1,
    "04": 1,
    "ARRAY": 4,
    "2014": 1,
    "glBindImageTextures": 4,
    "X": 1,
    "✔": 2,
    "BINDING": 12,
    "one": 1,
    "image": 14,
    "34": 2,
    "ONLY": 1,
    "distributed": 1,
    "zero": 11,
    "version": 1,
    "©": 1,
    "glGetTexParameter": 1,
    "must": 2,
    "or": 5,
    "of": 20,
    "pased": 1,
    "pseudo": 1,
    "Feature": 1,
    "have": 1,
    "are": 2,
    "positive": 1,
    "only": 2,
    "will": 4,
    "stored": 1,
    "RECTANGLE": 1,
    "state": 2,
    "examples": 1,
    "consecutive": 3,
    "used": 1,
    "*": 1,
    "which": 1,
    "existing": 5,
    "new": 1,
    "glGet": 1,
    "been": 3,
    "height": 1,
    "taken": 1,
    "for": 4,
    "level": 5,
    "TRUE": 1,
    "-": 14,
    "code": 1,
    "and": 5,
    "cannot": 1,
    "D": 10,
    "VersionFunction": 1,
    "that": 2,
    "Open": 1,
    "However": 1,
    "specifies": 1,
    "call": 2,
    "any": 4,
    "BUFFER": 1,
    "Publication": 1,
    "bind": 2,
    "with": 2,
    ":": 2,
    "READ": 2,
    "terms": 1,
    "command": 1,
    "Note": 1,
    "passed": 1,
    "textures": 18,
    "SupportOpenGL": 1,
    "more": 1,
    "create": 1,
    "forth": 1,
    "equivalent": 1,
    "present": 1,
    ",": 51,
    "/": 5,
    "objects": 3,
    "supported": 2,
    "changed": 1,
    "glBindImageTexture": 2,
    "02": 1,
    "1999": 1,
    "For": 1,
    "as": 1,
    "entry": 3,
    "array": 6,
    "appropriately": 1,
    "has": 1,
    "cube": 1,
    "implementation": 1,
    "other": 1,
    "once": 1,
    "layered": 1,
    "internal": 3,
    "parameter": 1,
    "higher": 1,
    "Specificationvoid": 1,
    "|": 2,
    "greater": 1,
    "June": 1,
    "named": 1,
    "to": 14,
    "the": 34,
    "address": 1,
    "_": 60,
    "GL": 21,
    "{": 5,
    "updated": 1,
    ";": 5,
    "names": 4,
    "+": 5,
    "Khronos": 1,
    "be": 8,
    "GLuint": 2,
    "then": 1,
    "by": 3
  },
  "docs.gl/gl4/glDebugMessageInsert.xhtml": {
    "forth": 1,
    "recorded": 1,
    "used": 2,
    "Name": 1,
    "by": 2,
    "APPLICATION": 1,
    "The": 7,
    "Publication": 1,
    "June": 1,
    "character": 3,
    "and": 7,
    "queue": 1,
    "in": 4,
    ".": 38,
    "SOURCE": 2,
    "any": 2,
    "SupportOpenGL": 1,
    "All": 1,
    "ENUM": 1,
    "id": 3,
    "may": 4,
    "DEPRECATED": 1,
    "1999": 1,
    "SEVERITY": 5,
    "reserved": 1,
    ";": 1,
    "—": 1,
    "(": 1,
    "contains": 1,
    "than": 2,
    "44": 1,
    "GL": 23,
    "PERFORMANCE": 1,
    "5": 1,
    "Khronos": 1,
    "source": 5,
    "14": 1,
    "openpub": 1,
    "This": 2,
    "conditions": 1,
    "8": 1,
    "LOW": 1,
    "generated": 2,
    "MESSAGE": 2,
    "©": 1,
    "identifier": 1,
    "value": 3,
    "LENGTH": 2,
    "opencontent": 1,
    "3": 1,
    "array": 3,
    "application": 2,
    "inserted": 1,
    "2": 1,
    "https": 1,
    "Copyright": 2,
    "GROUP": 4,
    "specifies": 1,
    "GLenum": 3,
    "constant": 1,
    "NotesGL": 1,
    "insert": 5,
    "containing": 1,
    "given": 2,
    "will": 2,
    "classify": 1,
    "an": 1,
    "inject": 1,
    "the": 27,
    "only": 1,
    "implicitly": 1,
    "not": 1,
    "NOTIFICATION": 2,
    "$": 2,
    "34": 2,
    "24": 1,
    ",": 25,
    "*": 1,
    "user": 2,
    "AlsoglDebugMessageControl": 1,
    ":": 1,
    "length": 7,
    "GLsizei": 1,
    "/": 5,
    "type": 6,
    "Group": 1,
    "NameglDebugMessageInsert": 1,
    "Specificationvoid": 1,
    "to": 9,
    "address": 3,
    "MARKER": 2,
    "then": 1,
    "-": 14,
    "count": 1,
    "contained": 1,
    "or": 7,
    "available": 2,
    "accepted": 1,
    "POP": 2,
    "See": 1,
    "material": 1,
    "TYPE": 12,
    "characters": 1,
    "supplied": 3,
    "implementation": 2,
    "Feature": 1,
    "02": 1,
    "greater": 1,
    "glGetDebugMessageLog": 1,
    "indicates": 2,
    "specified": 1,
    "INVALID": 2,
    "OTHER": 1,
    "License": 1,
    "HIGH": 1,
    "of": 14,
    "identify": 1,
    "Parameterssource": 1,
    "Open": 1,
    "v": 1,
    "org": 1,
    "whether": 1,
    "const": 1,
    "THIRD": 1,
    "MEDIUM": 1,
    "null": 1,
    "1": 1,
    "a": 4,
    "inserts": 1,
    "whose": 2,
    "BEHAVIOR": 2,
    "VALUE": 1,
    "DescriptionglDebugMessageInsert": 1,
    "PORTABILITY": 1,
    "output": 1,
    "GLuint": 1,
    "✔": 3,
    "distributed": 1,
    "_": 76,
    "one": 2,
    "glDebugMessageInsert": 2,
    "queueC": 1,
    "char": 1,
    "ERROR": 1,
    "defined": 2,
    "If": 1,
    "if": 3,
    "ErrorsGL": 1,
    "treated": 1,
    "DEBUG": 21,
    "must": 2,
    "PARTY": 1,
    "interface": 1,
    ")": 1,
    "higher": 1,
    "{": 2,
    "is": 10,
    "are": 2,
    "be": 9,
    "use": 2,
    "13": 2,
    "other": 1,
    "glDebugMessageCallback": 1,
    "message": 18,
    "version": 1,
    "severity": 6,
    "2014": 1,
    "string": 2,
    "subject": 1,
    "PUSH": 2,
    "0": 1,
    "as": 1,
    "terms": 1,
    "2013": 1,
    "VersionFunction": 1,
    "examples": 1,
    "Version": 1,
    "less": 1,
    "pipelinestall": 1,
    "}": 2,
    "into": 2,
    "for": 2,
    "4": 1,
    "types": 1,
    "terminated": 1,
    "set": 1,
    "03": 1,
    "messages": 1,
    "MAX": 2,
    "debug": 5,
    "negative": 1,
    "UNDEFINED": 1,
    "sources": 1,
    "23": 1,
    "that": 1,
    "explicitly": 1,
    "equal": 1,
    "04": 1
  },
  "docs.gl/gl4/glDepthRangeIndexed.xhtml": {
    "corresponding": 1,
    "Copyright": 1,
    "©": 1,
    "Notes": 1,
    "glDepthRangeIndexed": 4,
    "terms": 1,
    "coordinate": 1,
    "SupportOpenGL": 1,
    "change": 1,
    "RANGE": 1,
    "ErrorsGL": 1,
    "first": 1,
    "Specifies": 3,
    "greater": 1,
    "See": 1,
    "8": 1,
    "mappings": 1,
    "GLclampd": 1,
    "5": 1,
    "Khronos": 1,
    "value": 4,
    "specified": 4,
    "that": 1,
    "_": 8,
    "glPolygonOffset": 1,
    "for": 3,
    "utilized": 1,
    "13": 2,
    "2": 1,
    "AlsoglDepthFunc": 1,
    "though": 1,
    "GLuint": 1,
    "must": 1,
    "such": 1,
    "The": 5,
    "This": 2,
    "of": 13,
    "}": 2,
    "transparent": 1,
    "Parametersindex": 1,
    "MAX": 2,
    "detail": 1,
    "plane": 6,
    "Each": 1,
    "=": 2,
    "conditions": 1,
    "whose": 2,
    "type": 1,
    "clipping": 4,
    "Thus": 1,
    "It": 1,
    "described": 1,
    "VALUE": 1,
    "from": 4,
    "DEPTH": 1,
    "may": 1,
    "generated": 1,
    "mapping": 6,
    "VersionFunction": 1,
    "/": 5,
    "material": 1,
    "nearVal": 5,
    "With": 1,
    "changed": 1,
    "Open": 1,
    "glViewport": 1,
    "code": 1,
    "2014": 1,
    "1999": 1,
    "org": 1,
    "near": 5,
    "initial": 2,
    "be": 3,
    "this": 4,
    "by": 2,
    "Reverse": 1,
    "removedTypes": 1,
    "less": 2,
    "set": 1,
    "viewportC": 1,
    "components": 1,
    "2010": 1,
    "opencontent": 1,
    "(": 3,
    "normalized": 3,
    "an": 1,
    "NameglDepthRangeIndexed": 1,
    "Associated": 1,
    "Version": 1,
    "glDepthRangeArray": 1,
    "maps": 1,
    "specify": 2,
    "in": 4,
    "buffer": 2,
    "INVALID": 1,
    "farVal": 5,
    "as": 3,
    "After": 1,
    "both": 1,
    "equal": 1,
    "—": 1,
    "GLdouble": 3,
    "independent": 1,
    "GetsglGet": 1,
    "device": 1,
    "$": 2,
    "user": 1,
    "distributed": 1,
    "subject": 1,
    "Name": 1,
    "14": 1,
    "like": 1,
    "License": 1,
    ":": 1,
    "openpub": 1,
    "index": 5,
    "to": 16,
    "the": 25,
    "accepted": 2,
    "glViewportArray": 1,
    "range": 10,
    "a": 4,
    "linear": 2,
    "than": 3,
    "{": 2,
    "distance": 2,
    "w": 1,
    "23": 1,
    "page": 1,
    "parameter": 1,
    "24": 1,
    "forth": 1,
    "clamped": 1,
    "1": 8,
    "-": 9,
    "not": 1,
    "removedTypesCopyright": 1,
    "v": 1,
    "0": 6,
    "treated": 1,
    ";": 1,
    "Description": 1,
    ")": 3,
    "actual": 1,
    "specifies": 2,
    "fully": 1,
    "acceptable": 1,
    "with": 1,
    "pipelinestall": 1,
    "setting": 1,
    "GL": 3,
    "44": 1,
    "34": 2,
    "is": 8,
    "values": 4,
    "VIEWPORTS": 2,
    "✔": 5,
    "Group": 1,
    "https": 1,
    "Publication": 1,
    "far": 5,
    "04": 1,
    "Feature": 1,
    "division": 1,
    "color": 1,
    "on": 1,
    "respectively": 1,
    ".": 36,
    "update": 1,
    "03": 1,
    "before": 1,
    "implementation": 1,
    "are": 4,
    "planes": 1,
    "coordinates": 9,
    "viewport": 5,
    "they": 2,
    "argument": 1,
    "June": 1,
    "window": 6,
    "Specificationvoid": 1,
    "has": 1,
    "Regardless": 1,
    "through": 1,
    "necessary": 1,
    "depth": 13,
    "parameters": 1,
    "and": 10,
    ",": 18,
    "modify": 1,
    "was": 1,
    "if": 1,
    "or": 1,
    "examples": 1,
    "02": 1,
    "glDepthRange": 1
  },
  "docs.gl/gl4/glBindImageTexture.xhtml": {
    "Publication": 1,
    "distributed": 1,
    "equal": 1,
    "Version": 1,
    "material": 1,
    "Specificationvoid": 1,
    "UIrgba": 3,
    "to": 33,
    "name": 4,
    "terms": 1,
    "LAYER": 1,
    "v": 1,
    "$": 2,
    "g": 1,
    "read": 2,
    "03": 1,
    "zero": 3,
    "match": 1,
    "b": 1,
    "existing": 3,
    "compatible": 2,
    "following": 1,
    "34": 2,
    "—": 1,
    "8": 25,
    "parameter": 1,
    "D": 6,
    "TRUE": 1,
    "specifies": 7,
    "array": 7,
    "Frgba": 2,
    "44": 1,
    "glBindTextureCopyright": 1,
    "3": 2,
    "Notes": 1,
    "INVALID": 4,
    "License": 1,
    "openpub": 1,
    "_": 113,
    "UIrg": 3,
    "bound": 4,
    "ONLY": 3,
    "formats": 2,
    "writes": 1,
    "available": 1,
    "shaders": 3,
    "for": 5,
    "dimensional": 2,
    "RG": 12,
    "are": 1,
    "Qualifier": 1,
    "only": 4,
    "AlsoglGenTextures": 1,
    "02": 1,
    "listed": 1,
    "two": 2,
    "must": 2,
    "otherwise": 1,
    "formatted": 2,
    "on": 1,
    "Violation": 1,
    "When": 1,
    "BY": 2,
    "2014": 1,
    "results": 1,
    "Specification": 1,
    "SIZE": 1,
    "criterion": 1,
    "then": 3,
    "version": 1,
    "A": 2,
    "and": 7,
    ",": 36,
    "UIr": 3,
    "class": 1,
    "4": 1,
    "examples": 1,
    "conditions": 1,
    "undefined": 1,
    "R": 13,
    "matching": 1,
    "FORMAT": 4,
    "token": 1,
    "pipelinestall": 1,
    "of": 22,
    "access": 10,
    "will": 3,
    "SNORMrgba": 2,
    "2011": 1,
    "Unit": 1,
    "RGB": 2,
    "Feature": 1,
    "BINDING": 6,
    "WRITE": 2,
    "attach": 1,
    "return": 1,
    "READ": 3,
    "Internal": 1,
    "indicate": 1,
    "If": 3,
    "Frg": 2,
    "a": 15,
    "supported": 1,
    "glTexStorage": 3,
    "example": 1,
    "either": 1,
    "{": 2,
    "SupportOpenGL": 1,
    "1": 4,
    "CLASS": 1,
    "Formats": 1,
    "Fr": 3,
    ":": 1,
    "Associated": 1,
    "DescriptionglBindImageTexture": 1,
    "writing": 1,
    "binding": 2,
    "possible": 1,
    "table": 1,
    "when": 1,
    "Image": 2,
    "format": 10,
    "ErrorsGL": 1,
    "values": 1,
    "Copyright": 1,
    "such": 1,
    "object": 2,
    "snorm": 1,
    "long": 1,
    "calling": 1,
    "used": 2,
    "argument": 6,
    "MAX": 1,
    "lead": 1,
    "5": 1,
    "forth": 1,
    "performing": 1,
    "not": 3,
    "by": 3,
    "'": 1,
    "©": 1,
    "rgba": 2,
    "map": 2,
    "from": 2,
    "s": 1,
    "elements": 1,
    "OpenGL": 1,
    "entire": 2,
    "stores": 2,
    "value": 2,
    "size": 1,
    "GLuint": 2,
    "whether": 1,
    "specifying": 1,
    "ACCESS": 1,
    "cases": 1,
    "32": 18,
    "SNORMrg": 2,
    "need": 1,
    "texture": 24,
    "/": 5,
    "be": 12,
    "FALSE": 2,
    "single": 2,
    "F": 2,
    "04": 1,
    "GLboolean": 1,
    "See": 1,
    "11": 4,
    "reading": 1,
    "June": 1,
    ";": 1,
    "bind": 7,
    "glBindImageTexture": 3,
    "GLint": 2,
    "layer": 8,
    "purposes": 1,
    "fGL": 7,
    "layered": 6,
    "exactly": 1,
    "TYPE": 1,
    "rgb": 1,
    ")": 2,
    "multisample": 1,
    ".": 51,
    "than": 2,
    "Ir": 3,
    "based": 1,
    "1999": 1,
    "ignored": 1,
    "VersionFunction": 1,
    "termination": 1,
    "Ignored": 1,
    "SNORMr": 2,
    "possibly": 1,
    "with": 10,
    "NAME": 1,
    "three": 1,
    "it": 2,
    "uiGL": 10,
    "LEVEL": 1,
    "one": 3,
    "any": 1,
    "considered": 1,
    "(": 2,
    "treated": 1,
    "types": 1,
    "set": 4,
    "or": 10,
    "iGL": 9,
    "matches": 1,
    "Khronos": 1,
    "UIrgb": 1,
    "NameglBindImageTexture": 1,
    "attached": 1,
    "https": 1,
    "greater": 2,
    "This": 1,
    "established": 1,
    "}": 2,
    "binds": 1,
    "G": 1,
    "Parametersunit": 1,
    "unit": 16,
    "Irg": 3,
    "13": 2,
    "write": 2,
    "GL": 29,
    "r": 2,
    "glGet": 5,
    "f": 2,
    "unitC": 1,
    "indicating": 1,
    "image": 18,
    "the": 53,
    "performed": 2,
    "respectively": 2,
    "internal": 2,
    "Table": 1,
    "defined": 1,
    "level": 9,
    "determined": 1,
    "less": 1,
    "Format": 2,
    "type": 2,
    "IMAGE": 10,
    "subject": 1,
    "GetsglGet": 1,
    "as": 4,
    "LAYERED": 1,
    "2": 8,
    "opencontent": 1,
    "23": 1,
    "program": 1,
    "into": 1,
    "Group": 1,
    "org": 1,
    "purpose": 1,
    "index": 2,
    "if": 8,
    "broken": 1,
    "Specifies": 6,
    "that": 4,
    "is": 22,
    "-": 17,
    "specified": 1,
    "10": 6,
    "0": 1,
    "Name": 1,
    "generated": 4,
    "16": 30,
    "B": 1,
    "Irgba": 3,
    "VALUE": 3,
    "24": 1,
    "may": 3,
    "However": 1,
    "shader": 1,
    "The": 2,
    "ENUM": 1,
    "including": 1,
    "14": 1,
    "GLenum": 2,
    "snormGL": 5,
    "glGetTexParameter": 1,
    "glTexImage": 3,
    "given": 1,
    "an": 6,
    "Open": 1,
    "in": 4,
    "UNITS": 1,
    "COMPATIBILITY": 3,
    "tokens": 1,
    "cube": 2,
    "In": 1,
    "✔": 4,
    "rg": 2,
    "RGBA": 12,
    "which": 2
  },
  "docs.gl/gl4/glVertexBindingDivisor.xhtml": {
    "/": 5,
    "$": 2,
    "and": 2,
    "zero": 3,
    "with": 2,
    "attributes": 4,
    "as": 1,
    "04": 1,
    "ATTRIB": 2,
    "than": 1,
    ";": 2,
    "Associated": 1,
    "array": 5,
    "command": 1,
    "opencontent": 1,
    "03": 1,
    "ErrorsGL": 1,
    "greater": 1,
    "DIVISOR": 1,
    "AlsoglBindVertexBuffer": 1,
    "Copyright": 2,
    "material": 1,
    "bound": 3,
    "object": 5,
    "function": 1,
    "An": 1,
    "GLuint": 5,
    "2": 1,
    "may": 1,
    "primitives": 1,
    "Publication": 1,
    "a": 1,
    "the": 16,
    "vaobj": 3,
    "License": 1,
    "23": 1,
    "non": 2,
    "5": 1,
    "0": 1,
    "value": 3,
    "of": 8,
    "index": 1,
    "divisorThe": 1,
    "which": 2,
    "if": 4,
    "existing": 1,
    "glVertexAttribBinding": 1,
    "binding": 1,
    "buffer": 1,
    "terms": 1,
    "openpub": 1,
    "44": 1,
    "VersionFunction": 1,
    "uses": 1,
    "(": 3,
    "Open": 1,
    "new": 1,
    "Name": 1,
    "MAX": 2,
    "14": 1,
    "generated": 3,
    "Feature": 1,
    "referred": 1,
    "examples": 1,
    "using": 1,
    "glVertexAttribPointer": 2,
    "If": 2,
    ",": 14,
    ".": 30,
    "instances": 2,
    "VALUE": 1,
    "rendered": 1,
    "not": 1,
    "multiple": 1,
    "instance": 1,
    "BINDING": 1,
    "state": 1,
    "in": 2,
    "INVALID": 3,
    "bindingindex": 4,
    "24": 1,
    "See": 1,
    "1": 1,
    ":": 1,
    "vertices": 1,
    "whereas": 1,
    "distributed": 1,
    "GL": 5,
    "being": 1,
    "modify": 3,
    "corresponding": 1,
    "02": 1,
    "8": 1,
    "conditions": 1,
    "bindingindexThe": 1,
    "to": 6,
    "glVertexArrayBindingDivisor": 7,
    "OPERATION": 2,
    "no": 1,
    "{": 2,
    "void": 1,
    "advance": 3,
    "at": 2,
    "updates": 1,
    "divisor": 7,
    "ParametersvaobjSpecifies": 1,
    "This": 1,
    "instanced": 1,
    "13": 2,
    "vertex": 8,
    "}": 2,
    "whose": 1,
    "BINDINGS": 2,
    "34": 2,
    "pipelinestall": 1,
    "by": 2,
    "per": 2,
    "2013": 1,
    "generic": 2,
    "SupportOpenGL": 1,
    "org": 1,
    "step": 1,
    "subject": 1,
    "arguments": 1,
    "Version": 1,
    "rate": 3,
    "VERTEX": 3,
    "DescriptionglVertexBindingDivisor": 1,
    "https": 1,
    "currently": 1,
    "NameglVertexBindingDivisor": 1,
    "Specificationvoid": 1,
    "is": 10,
    "June": 1,
    "when": 1,
    "set": 2,
    "1999": 1,
    "advanceC": 1,
    ")": 3,
    "attribute": 1,
    "v": 1,
    "-": 23,
    "✔": 4,
    "once": 2,
    "_": 17,
    "2014": 1,
    "Khronos": 1,
    "—": 1,
    "s": 1,
    "forth": 1,
    "Group": 1,
    "GetsglGet": 1,
    "apply": 1,
    "rendering": 1,
    "ID": 1,
    "equal": 1,
    "glVertexBindingDivisor": 5,
    "name": 2,
    "©": 1,
    "be": 1,
    "single": 1,
    "for": 2,
    "an": 1,
    "draw": 1,
    "or": 1
  },
  "docs.gl/gl4/glGenFramebuffers.xhtml": {
    "an": 1,
    "used": 1,
    "opencontent": 1,
    ":": 1,
    "form": 1,
    "it": 1,
    "glDeleteFramebuffers": 1,
    "generated": 2,
    "only": 2,
    "none": 1,
    "type": 1,
    "INVALID": 1,
    "See": 1,
    "Publication": 1,
    "number": 1,
    "unless": 1,
    "guaranteed": 1,
    "marked": 1,
    "Specificationvoid": 1,
    "by": 2,
    "VersionFunction": 1,
    "1999": 1,
    "org": 1,
    "$": 2,
    "}": 2,
    "✔": 10,
    "negative": 1,
    "namesC": 1,
    "AlsoglBindFramebuffer": 1,
    "Open": 1,
    ";": 2,
    "in": 5,
    "of": 4,
    "returned": 4,
    "This": 1,
    "no": 1,
    "are": 5,
    "with": 1,
    "for": 1,
    "may": 1,
    "integers": 1,
    "names": 7,
    "glGenFramebuffers": 5,
    "*": 1,
    "Khronos": 1,
    "glDeleteFramebuffersCopyright": 1,
    "{": 2,
    "2014": 1,
    "conditions": 1,
    "set": 2,
    "03": 1,
    "Feature": 1,
    "©": 1,
    ")": 1,
    "GLsizei": 1,
    "NameglGenFramebuffers": 1,
    "02": 1,
    "GLuint": 1,
    "that": 2,
    "The": 1,
    "forth": 1,
    "object": 5,
    "contiguous": 1,
    "immediately": 1,
    "they": 3,
    "Specifies": 2,
    "v": 1,
    "which": 1,
    "call": 2,
    "returns": 1,
    "and": 2,
    "44": 1,
    "1": 1,
    "use": 1,
    "VALUE": 1,
    "deleted": 1,
    "but": 1,
    "https": 1,
    "23": 1,
    "openpub": 1,
    ".": 24,
    "as": 1,
    "purposes": 1,
    "There": 1,
    "first": 2,
    "5": 1,
    "when": 1,
    "24": 1,
    "2": 1,
    "a": 2,
    "2010": 1,
    "/": 5,
    "not": 1,
    "ErrorsGL": 1,
    "stored": 1,
    "Group": 1,
    "examples": 1,
    "14": 1,
    "Copyright": 1,
    "guarantee": 1,
    "however": 1,
    "before": 1,
    "04": 1,
    "material": 1,
    "was": 1,
    "—": 1,
    "n": 3,
    "subject": 1,
    "License": 1,
    "array": 1,
    "subsequent": 1,
    "framebuffer": 4,
    "to": 4,
    "0": 1,
    "Parametersn": 1,
    "DescriptionglGenFramebuffers": 1,
    "generate": 2,
    "ids": 4,
    "(": 1,
    "bound": 1,
    "acquire": 1,
    "Version": 1,
    "June": 1,
    "13": 2,
    "distributed": 1,
    "state": 1,
    "34": 2,
    "calls": 1,
    "terms": 1,
    "Name": 1,
    ",": 8,
    "Framebuffer": 1,
    "the": 8,
    "_": 2,
    "is": 4,
    "if": 1,
    "-": 3,
    "pipelinestall": 1,
    "SupportOpenGL": 1,
    "8": 1,
    "be": 1
  },
  "docs.gl/gl4/glGetTexParameter.xhtml": {
    "RED": 1,
    "an": 5,
    "RReturns": 1,
    "glCreateTextures": 1,
    "pnameSpecifies": 1,
    "constant": 8,
    "layers": 1,
    "glGetTexParameterfv": 3,
    "4": 3,
    "depth": 1,
    "comparison": 2,
    "wrapping": 3,
    "existing": 1,
    "glGetTextureParameter": 4,
    "see": 1,
    "use": 1,
    "texturing": 1,
    "BASE": 2,
    "minification": 1,
    "and": 8,
    "glTextureView": 5,
    "—": 1,
    "LAYERSReturns": 1,
    "5": 2,
    "FreeB": 1,
    "LAYERReturns": 1,
    "}": 2,
    "details": 1,
    "BORDER": 2,
    "04": 1,
    "COMPARE": 4,
    "_": 287,
    "with": 3,
    "NameglGetTexParameter": 1,
    "is": 36,
    "Floating": 1,
    "2": 13,
    "MIPMAP": 1,
    "BLUE": 1,
    "was": 2,
    "LAYER": 2,
    "G": 1,
    "immutable": 3,
    "stencil": 1,
    "NONE": 2,
    "projects": 1,
    "FALSE": 1,
    "R": 3,
    "MAP": 4,
    "ARRAY": 8,
    "ParameterstargetSpecifies": 1,
    "three": 1,
    "GL": 102,
    "respectively": 1,
    "all": 1,
    "effective": 2,
    "specified": 2,
    "{": 2,
    "examples": 1,
    "in": 5,
    "/": 11,
    "that": 3,
    "LEVELSReturns": 2,
    "matching": 1,
    "SWIZZLE": 10,
    "RGBA": 2,
    "dimensional": 5,
    "MODEReturns": 2,
    "representable": 2,
    "Specificationvoid": 1,
    "SupportOpenGL": 1,
    "BIAS": 1,
    "2006": 1,
    "set": 1,
    "1": 9,
    "LAYERS": 2,
    "specify": 1,
    "1000": 3,
    "DEPTH": 4,
    "$": 2,
    "GLfloat": 2,
    "return": 3,
    "valuesC": 1,
    "levels": 2,
    "t": 1,
    "glGetTex": 1,
    "under": 1,
    "LEVELReturns": 3,
    "For": 3,
    "34": 2,
    "*": 11,
    "14": 1,
    "such": 1,
    "criteria": 1,
    "pname": 11,
    "of": 18,
    "same": 2,
    "24": 1,
    "Copyright": 2,
    "texture": 39,
    "alpha": 1,
    "2010": 1,
    "IMAGE": 5,
    "FUNC": 1,
    "License": 1,
    "by": 2,
    "or": 12,
    "symbolic": 9,
    "glGetTextureParameterIuiv": 3,
    "TYPEReturns": 1,
    "This": 1,
    "RECTANGLE": 2,
    "INVALID": 3,
    "mipmap": 2,
    "glGetTextureParameterIiv": 3,
    "GReturns": 1,
    "CLASS": 1,
    "03": 1,
    "single": 18,
    "web": 2,
    "GREEN": 1,
    "MAX": 4,
    "become": 1,
    "01": 1,
    "TEXTURE": 78,
    "maps": 2,
    "GLenum": 12,
    "greater": 3,
    "void": 7,
    "glTextureStorage": 3,
    "FILTERReturns": 2,
    "to": 10,
    "call": 1,
    "GLint": 4,
    "GLuint": 6,
    "LINEAR": 2,
    "accepts": 1,
    "functions": 3,
    "LODReturns": 1,
    "function": 4,
    "target": 12,
    "generated": 4,
    "ENUM": 2,
    "first": 1,
    "Can": 1,
    "NEAREST": 1,
    "glTexParameter": 4,
    "as": 4,
    "coordinate": 3,
    "its": 2,
    "glGetTexParameterIiv": 3,
    "LEVEL": 4,
    "it": 2,
    "error": 2,
    "version": 3,
    "licensed": 1,
    "are": 6,
    "blue": 1,
    "Textures": 1,
    "this": 1,
    "A": 1,
    "two": 4,
    "number": 3,
    "Silicon": 1,
    "filter": 2,
    "NUM": 6,
    "parameter": 5,
    "symbols": 1,
    "AReturns": 1,
    "values": 3,
    "used": 1,
    "change": 1,
    "In": 1,
    "Parameter": 1,
    "©": 2,
    "r": 1,
    "following": 1,
    "20171022161616": 1,
    "Integer": 1,
    "glGetTextureParameteriv": 3,
    "the": 53,
    "representation": 1,
    "The": 19,
    "23": 1,
    "not": 3,
    "Version": 1,
    "VIEW": 12,
    "object": 3,
    "mapped": 2,
    "Software": 1,
    "glGetTexParameterIuiv": 3,
    "mapping": 1,
    "NotesIf": 1,
    "02": 1,
    "level": 6,
    "TARGETReturns": 1,
    "bound": 2,
    "FILTER": 2,
    "glGetTexParameter": 2,
    "created": 2,
    "oss": 1,
    "params": 10,
    "WRAP": 6,
    "SIZE": 1,
    ")": 9,
    "CUBE": 4,
    "color": 1,
    "name": 3,
    "returned": 2,
    "OPERATION": 1,
    "negative": 1,
    ".": 99,
    "value": 25,
    "glGetTexParameteriv": 3,
    "3": 6,
    "0": 8,
    "BReturns": 1,
    "multisample": 2,
    "s": 1,
    "has": 1,
    "sgi": 1,
    "Returns": 5,
    "SGI": 1,
    "red": 1,
    "zero": 1,
    "valued": 16,
    "-": 87,
    "query": 1,
    "magnification": 1,
    "T": 2,
    "textureSpecifies": 1,
    "2014": 1,
    "border": 1,
    "targets": 1,
    "channels": 1,
    "positive": 1,
    "initially": 1,
    "FORMATReturns": 1,
    "DescriptionglGetTexParameter": 1,
    "swizzle": 5,
    "glTextureParameter": 1,
    "their": 1,
    "See": 8,
    "component": 5,
    "https": 1,
    "D": 23,
    "green": 1,
    "only": 4,
    "made": 1,
    "initial": 19,
    "non": 1,
    "✔": 48,
    "org": 1,
    "COMPATIBILITY": 5,
    ",": 108,
    "linear": 1,
    "numbers": 1,
    "contents": 1,
    "ALPHA": 1,
    "glTexStorage": 6,
    "13": 2,
    "AlsoglTexParameter": 1,
    "glTextureViewCopyright": 1,
    "Free": 1,
    "which": 3,
    "VersionFunction": 1,
    "1991": 1,
    "BY": 2,
    "http": 1,
    "TYPE": 2,
    "parameters": 3,
    "Group": 1,
    "MIN": 10,
    "image": 1,
    "minimum": 1,
    "paramsReturns": 1,
    "addition": 1,
    "Khronos": 1,
    "document": 1,
    "storage": 1,
    "mode": 2,
    "REPEAT": 3,
    "cube": 2,
    "base": 2,
    "RGBAReturns": 1,
    "a": 23,
    "range": 1,
    "point": 3,
    "accepted": 4,
    "may": 1,
    "com": 1,
    "glGetTextureParameterfv": 3,
    "STENCIL": 3,
    "FUNCReturns": 1,
    "format": 1,
    "ErrorsGL": 1,
    "B": 2,
    "if": 8,
    "pipelinestall": 1,
    "for": 7,
    "44": 1,
    "TARGET": 2,
    "one": 3,
    "no": 1,
    "Graphics": 1,
    "comprise": 1,
    "Inc": 1,
    "MODE": 3,
    "interpretations": 1,
    "view": 5,
    "read": 1,
    "archive": 1,
    "COMPONENT": 1,
    "detail": 3,
    "COLOR": 2,
    "be": 1,
    "when": 2,
    "rectangle": 1,
    "Feature": 1,
    "parent": 2,
    "FORMAT": 6,
    "LOD": 4,
    "IMMUTABLE": 5,
    "S": 2,
    "accept": 1,
    "relative": 2,
    "LEVELS": 4,
    "maximum": 2,
    "(": 9,
    "MULTISAMPLE": 4,
    ";": 8,
    ":": 4,
    "MAG": 2,
    "array": 7,
    "integer": 3,
    "Name": 1,
    "available": 3,
    "internal": 1,
    "most": 2,
    "LEQUAL": 1,
    "defines": 1,
    "floating": 2,
    "four": 1
  },
  "docs.gl/gl4/glCreateBuffers.xhtml": {
    "in": 3,
    "glBindBufferRange": 1,
    "it": 1,
    "initialized": 1,
    "Publication": 1,
    "✔": 1,
    "each": 1,
    "ErrorsGL": 1,
    "https": 1,
    "*": 1,
    "new": 2,
    ")": 1,
    "stored": 1,
    "34": 2,
    "02": 1,
    "openpub": 1,
    "glBindBufferBase": 1,
    "glIsBufferCopyright": 1,
    "—": 1,
    "n": 3,
    "if": 2,
    "See": 1,
    "which": 1,
    "the": 4,
    "glUnmapBuffer": 1,
    "Copyright": 1,
    "previously": 1,
    "0": 1,
    "had": 1,
    "material": 1,
    "VersionFunction": 1,
    "{": 2,
    "License": 1,
    "Khronos": 1,
    "Group": 1,
    "8": 1,
    "glMapBuffer": 1,
    "subject": 1,
    "set": 1,
    "as": 1,
    "is": 2,
    "DescriptionglCreateBuffers": 1,
    "-": 11,
    "be": 1,
    ":": 1,
    "examples": 1,
    "AlsoglGenBuffers": 1,
    "objectsC": 1,
    "Feature": 1,
    "14": 1,
    "13": 2,
    "create": 2,
    ",": 11,
    "object": 1,
    "generated": 1,
    "number": 1,
    "bound": 1,
    "pipelinestall": 1,
    "names": 2,
    "Version": 1,
    "glDeleteBuffers": 1,
    "array": 1,
    "may": 1,
    "INVALID": 1,
    "Parametersn": 1,
    ";": 1,
    "terms": 1,
    "Specificationvoid": 1,
    "1999": 1,
    "VALUE": 1,
    "negative": 1,
    "GLsizei": 1,
    "$": 2,
    "and": 1,
    "conditions": 1,
    "buffer": 5,
    "_": 2,
    "of": 2,
    "objects": 2,
    "Name": 1,
    "returns": 1,
    "org": 1,
    "SupportOpenGL": 1,
    "2014": 1,
    "v": 1,
    "23": 1,
    "/": 5,
    "(": 1,
    "04": 1,
    "been": 1,
    "44": 1,
    "NameglCreateBuffers": 1,
    "}": 2,
    "2": 1,
    "unspecified": 1,
    "buffers": 3,
    "target": 1,
    "unused": 1,
    "June": 1,
    "a": 1,
    "©": 1,
    "This": 1,
    "to": 3,
    "glCreateBuffers": 2,
    "Specifies": 2,
    "opencontent": 1,
    "Open": 1,
    "5": 1,
    "24": 1,
    "glGet": 1,
    ".": 21,
    "03": 1,
    "an": 2,
    "1": 1,
    "are": 1,
    "distributed": 1,
    "GLuint": 1,
    "forth": 1,
    "representing": 1
  },
  "docs.gl/gl4/glDeleteFramebuffers.xhtml": {
    "Name": 1,
    "other": 1,
    "44": 1,
    "to": 5,
    "more": 1,
    "5": 1,
    "one": 1,
    "zero": 2,
    "in": 3,
    "The": 1,
    "GLuint": 1,
    "1999": 1,
    "reserved": 1,
    "silently": 1,
    "bound": 1,
    "SupportOpenGL": 1,
    "by": 2,
    "glCheckFramebufferStatusCopyright": 1,
    "14": 1,
    "unused": 2,
    "8": 1,
    "examples": 1,
    "names": 2,
    "FRAMEBUFFER": 2,
    "This": 1,
    "Copyright": 1,
    "June": 1,
    "is": 9,
    "glBindFramebuffer": 2,
    "✔": 10,
    "delete": 1,
    "{": 2,
    "0": 1,
    "https": 1,
    "had": 1,
    "-": 3,
    "set": 1,
    "terms": 1,
    "be": 3,
    ";": 1,
    ")": 1,
    "ErrorsGL": 1,
    "Open": 1,
    "conditions": 1,
    "Version": 1,
    "Once": 1,
    "_": 6,
    "2": 1,
    "object": 1,
    "License": 1,
    "GL": 3,
    "generated": 1,
    "23": 1,
    "if": 1,
    "2014": 1,
    "1": 1,
    "13": 2,
    "—": 1,
    "occur": 1,
    "has": 1,
    "addressed": 1,
    "targets": 1,
    "an": 1,
    "that": 1,
    "openpub": 1,
    ",": 9,
    "number": 1,
    "no": 1,
    "INVALID": 1,
    "*": 1,
    "of": 2,
    "a": 2,
    "attachments": 1,
    "pipelinestall": 1,
    "stored": 1,
    "deletes": 1,
    "objects": 3,
    ".": 24,
    "name": 2,
    "or": 2,
    "AlsoglGenFramebuffers": 1,
    "Specificationvoid": 1,
    "VALUE": 1,
    "may": 1,
    "framebuffer": 7,
    "(": 1,
    "distributed": 1,
    "/": 5,
    "VersionFunction": 1,
    "and": 4,
    "though": 1,
    "should": 1,
    "n": 4,
    "©": 1,
    "as": 2,
    "Group": 1,
    "material": 1,
    "with": 1,
    "target": 1,
    "deleted": 4,
    "DRAW": 1,
    "Feature": 1,
    "34": 2,
    "Publication": 1,
    "glDeleteFramebuffers": 2,
    "containing": 1,
    "it": 3,
    "negative": 1,
    "Parametersn": 1,
    "02": 1,
    "03": 1,
    ":": 1,
    "$": 2,
    "}": 2,
    "2010": 1,
    "whose": 1,
    "subject": 1,
    "24": 1,
    "READ": 1,
    "the": 8,
    "Specifies": 1,
    "GLsizei": 1,
    "are": 2,
    "framebuffers": 4,
    "been": 1,
    "org": 1,
    "array": 2,
    "04": 1,
    "DescriptionglDeleteFramebuffers": 1,
    "currently": 1,
    "A": 1,
    "executed": 1,
    "its": 1,
    "v": 1,
    "opencontent": 1,
    "Khronos": 1,
    "corresponding": 1,
    "again": 1,
    "ignored": 1,
    "forth": 1,
    "If": 1,
    "See": 1,
    "objectsC": 1,
    "pointer": 1,
    "NameglDeleteFramebuffers": 1
  },
  "docs.gl/gl4/glFramebufferTextureLayer.xhtml": {
    "ARRAY": 1,
    "than": 6,
    "attachment": 9,
    "34": 2,
    "}": 3,
    "these": 1,
    "texture": 26,
    "the": 33,
    "For": 4,
    "single": 2,
    "is": 32,
    "left": 1,
    "44": 1,
    "attach": 5,
    "buffers": 1,
    "{": 3,
    "Copyright": 1,
    "greater": 2,
    "targets": 2,
    "name": 6,
    "OPERATION": 4,
    "forth": 1,
    "ErrorsGL": 1,
    "opencontent": 1,
    "translated": 2,
    "generated": 9,
    "GL": 26,
    "—": 1,
    "may": 2,
    "lfloor": 1,
    "Name": 1,
    "map": 6,
    "This": 1,
    "simultaneously": 1,
    "distributed": 1,
    "conditions": 1,
    "License": 1,
    "8": 1,
    "multisample": 2,
    "©": 1,
    "bmod": 2,
    "Group": 1,
    "must": 5,
    "target": 5,
    "over": 1,
    "(": 4,
    "3": 2,
    "If": 3,
    "DRAW": 2,
    "MAX": 5,
    "INVALID": 9,
    "FRAMEBUFFER": 5,
    "by": 4,
    "as": 3,
    "02": 1,
    "14": 1,
    "logical": 3,
    "24": 1,
    "points": 2,
    "then": 2,
    "subject": 1,
    "v": 1,
    "a": 14,
    "GLuint": 3,
    "which": 2,
    "read": 1,
    "glFramebufferTextureLayer": 4,
    "are": 1,
    "bound": 3,
    "two": 5,
    "less": 2,
    "2": 3,
    "attaching": 1,
    "face": 4,
    "glFramebufferTexture": 3,
    "described": 1,
    "$": 18,
    "above": 1,
    "glFramebufferTextureFaceCopyright": 1,
    "2010": 1,
    "June": 1,
    "Specifies": 6,
    "org": 1,
    "openpub": 1,
    "ATTACHMENTand": 1,
    "minus": 3,
    "Parameterstarget": 1,
    "Textures": 1,
    "https": 1,
    "objects": 2,
    "so": 1,
    ")": 4,
    "specifies": 1,
    "Attaching": 1,
    "both": 1,
    "set": 1,
    "READ": 1,
    "0": 1,
    "if": 9,
    "mipmap": 1,
    "existing": 3,
    "GLenum": 3,
    "-": 26,
    "draw": 1,
    "that": 2,
    "Specificationvoid": 1,
    "SIZE": 3,
    "SupportOpenGL": 1,
    "6": 3,
    "from": 1,
    "13": 2,
    "terms": 1,
    ":": 1,
    "See": 1,
    "glNamedFramebufferTextureLayer": 6,
    "glGenRenderbuffers": 1,
    "for": 5,
    "COLOR": 3,
    "it": 1,
    "cannot": 1,
    "dimensional": 10,
    "textures": 2,
    "accepted": 2,
    "range": 1,
    "buffer": 2,
    "framebuffer": 15,
    "point": 1,
    "or": 12,
    "they": 1,
    "ATTACHMENTi": 2,
    "TEXTURE": 4,
    "LAYERS": 1,
    "layer": 13,
    "valid": 1,
    "equal": 4,
    "5": 1,
    "GLint": 4,
    "DescriptionglFramebufferTextureLayer": 1,
    "cube": 6,
    "supported": 1,
    "2014": 1,
    "DEPTH": 4,
    "i": 1,
    "NameglFramebufferTextureLayer": 1,
    "VersionFunction": 1,
    "1": 1,
    "zero": 9,
    "object": 10,
    "value": 5,
    "array": 11,
    "objectC": 1,
    "an": 4,
    "three": 5,
    "ATTACHMENT": 5,
    "ATTACHMENTS": 1,
    "log": 2,
    "into": 2,
    "according": 2,
    "ENUM": 2,
    "equivalent": 2,
    "k": 2,
    "negative": 1,
    "_": 64,
    "\\": 7,
    "/": 5,
    "examples": 1,
    "03": 1,
    "Feature": 1,
    "23": 1,
    "void": 1,
    "✔": 11,
    "Publication": 1,
    "and": 12,
    "commands": 1,
    "VALUE": 3,
    "default": 1,
    "right": 1,
    ";": 2,
    "material": 1,
    "of": 26,
    "not": 11,
    "in": 2,
    "glNamedFramebufferTexture": 1,
    "pipelinestall": 1,
    ",": 37,
    "to": 19,
    "one": 8,
    "attached": 1,
    "STENCIL": 4,
    "Version": 1,
    "glBindFramebuffer": 1,
    "1999": 1,
    "AlsoglGenFramebuffers": 1,
    "=": 3,
    "D": 2,
    "rfloor": 1,
    "larger": 2,
    "Khronos": 1,
    "Open": 1,
    "04": 1,
    "level": 10,
    "specified": 1,
    ".": 45,
    "be": 7
  }
}
"#;
